# Generated by Django 3.0.3 on 2020-02-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('food_in', models.CharField(max_length=20)),
                ('expiration_date', models.DateTimeField(verbose_name='expiration date')),
            ],
        ),
    ]
